name       : plexhometheater
version    : 1.4.1.469
release    : 1
source     :
    - https://github.com/plexinc/plex-home-theater-public/archive/v1.4.1.469-47a90f01.tar.gz : 82a0b3314de18e0f1bdb123c6fe4d411e147b052a09219a9d2057459dc0f36b3
license    : GPL-2.0
summary    : Plex Home Theater
description: |
    Plex Home Theater full-screen media player.
builddeps  :
    - libboost-devel
    - libjpeg-turbo-devel
    - libmad-devel
    - lzo-devel
    - swig
    - xrandr
    - pkgconfig(alsa)
    - pkgconfig(avahi-core)
    - pkgconfig(expat)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libavcodec)
    - pkgconfig(libcdio)
    - pkgconfig(libcec)
    - pkgconfig(libmicrohttpd)
    - pkgconfig(libmpeg2)
    - pkgconfig(libpcre)
    - pkgconfig(libplist)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(libva)
    - pkgconfig(samplerate)
    - pkgconfig(sdl)
    - pkgconfig(sdl_image)
    - pkgconfig(sdl_mixer)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(tinyxml2)
    - pkgconfig(vdpau)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(yajl)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
